[tool.poetry]
name = "ip-reveal"
version = "1.3a5"
description = "A GUI-based widget that checks your IP address periodically, sending notifications if it changes."
authors = ["Taylor B. <tayjaybabee@gmail.com>"]
license = "WTFPL"

[tool.poetry.dependencies]
humanize = "^3.1.0"
inspy_logger = "2.1a14"
inspyred_print = "^1.0"
PySimpleGUI = "^4.30.0"
PySimpleGUIQt = "^0.35.0"
python = ">=3.8,<3.11"
requests = "^2.25.0"
simpleaudio = { version = "^1.0.4", optional = true }
pypattyrn = "^1.2"
inspyre-toolbox = "1.3.1.dev2"
PySide2 = "^5.15.2"
toml = "^0.10.2"
johnnydep = "^1.10"
pyperclip = "^1.8.2"



[tool.poetry.dev-dependencies]
Sphinx = "^3.4.1"
changelog-generator = "^0.2.4"
pre-commit = "^2.15.0"
recommonmark = "^0.7.1"
imwatchingyou = "^2.3.0"
PyFuncExtras = "^0.0.1"

[tool.poetry.extras]
uniAudio = ["simpleaudio"]

[tool.poetry.scripts]
ip-reveal = 'ip_reveal:main'

[build-system]
requires = ["poetry-core>=0.12"]
build-backend = "poetry.core.masonry.api"
